name: Build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [8-jdk, 11-jdk, 16-jdk, 17-jdk]
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:${{ matrix.java }}
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build publishToMavenLocal --stacktrace --warning-mode fail
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/

  publish:
    needs: build
    runs-on: ubuntu-20.04
    container:
      image: openjdk:16-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build publish refreshMeta --stacktrace
        env:
          SNAPSHOTS_URL: ${{ secrets.SNAPSHOTS_URL }}
          SNAPSHOTS_USERNAME: ${{ secrets.SNAPSHOTS_USERNAME }}
          SNAPSHOTS_PASSWORD: ${{ secrets.SNAPSHOTS_PASSWORD }}
