name: Release
on: [workflow_dispatch] # Manual trigger
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: eclipse-temurin:17-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v1
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew checkVersion build publish refreshMeta github --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
          GITHUB_TOKEN: ${{ secrets.GH_API_KEY }}
          META_UPDATE_URL: ${{ secrets.META_UPDATE_URL }}
